env:
  browser: true
  es2021: true
extends:
  - "airbnb-base"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "eslint-plugin-import-helpers"
  - "eslint-plugin-jest"
  - "prettier"
rules:
  {
    radix: "error",
    no-console: "off",
    import/prefer-default-export: "off",
    no-self-compare: "error",
    implicit-arrow-linebreak: ["error", "beside"],
    no-compare-neg-zero: "error",
    no-dupe-else-if: "error",
    no-tabs: ["warn", { allowIndentationTabs: true }],
    no-mixed-spaces-and-tabs: ["error"],
    no-irregular-whitespace: ["error", { skipTemplates: true }],
    array-callback-return: "error",
    operator-linebreak: [2, "before", { overrides: { "?": "after" } }],
    block-scoped-var: "error",
    eqeqeq: ["error", "always"],
    max-len: ["error", { code: 90, tabWidth: 2 }],
    object-curly-newline: ["error", { consistent: true }],
    newline-per-chained-call: ["error", { ignoreChainWithDepth: 2 }],
    complexity: ["warn", { max: 5 }],
    treatUndefinedAsUnspecified: "off",
    class-methods-use-this: "off",
    no-param-reassing: "off",
    no-underscore-dangle: "off",
    import/no-extraneous-dependencies: ["off", { devDependencies: true }],
    import/extensions: ["off", "ignorePackages", { ts: "never", tsx: "never" }],
    lines-around-comment:
      [
        "error",
        {
          "beforeBlockComment": true,
          "afterBlockComment": true,
          "beforeLineComment": false,
          "afterLineComment": false,
          "allowBlockStart": true,
          "allowBlockEnd": true,
          "allowObjectStart": true,
          "allowObjectEnd": true,
          "allowArrayStart": true,
          "allowArrayEnd": true,
        },
      ],
    no-confusing-arrow: ["error", { "allowParens": false }],
    eslint-import-resolver-node: "off",
    no-mixed-operators: "error",
    no-unexpected-multiline: "error",
    quotes: ["error", "backtick"],
    import/no-unresolved: "off",
    import/named: 1,
    import/namespace: 1,
    import/default: 1,
    import/export: 1,
    import/no-useless-path-segments: 1,
    semi: "error",
    import-helpers/order-imports:
      ["warn", { newlinesBetween: "always", groups: [
              "module",
              /^
              (assert
              |async_hooks
              |buffer
              |child_process
              |cluster
              |console
              |constants
              |crypto
              |dgram
              |dns
              |domain
              |events
              |fs
              |http
              |http2
              |https
              |inspector
              |module
              |net
              |os
              |path
              |perf_hooks
              |process
              |punycode
              |querystring
              |readline
              |repl
              |stream
              |string_decoder
              |timers
              |tls
              |trace_events
              |tty
              |url
              |util
              |v8
              |vm
              |zli
              )/,
            ], alphabetize: { order: "asc", ignoreCase: true } }],
    jest/no-disabled-tests: "warn",
    jest/no-focused-tests: "error",
    jest/no-identical-title: "error",
    jest/prefer-to-have-length: "warn",
    jest/valid-expect: "error",
  }
